version: "3.9"

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DJANGO_SECRET_KEY=django-insecure-h#$5@pgi-%v!^-30v&*-s##86+@c@4qr!%hw!+_#mbk4tm_tg9
      - DJANGO_DEBUG=True
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    
volumes:
  postgres_data: